# **Finding highly-rated restaurants in Las Vegas, Nevada**
### ***Here are the types of food and neighborhoods you should try next***

***

### **General Project Information**

* A full report of this analysis can be found [here](Report.html). 

* The repo is for this analysis can be found [here](https://github.com/anukafi/finalproject.github.io.git).

* This analysis uses data from Yelp.com. The original dataset can be found [here](https://www.kaggle.com/yelp-dataset/yelp-dataset/version/6), but since these files were very large, we filtered to find only datapoints in Las Vegas. The subset used in this analysis can be found [here](https://drive.google.com/drive/folders/1pv1kB8oF7DLqWeWaSoDqLAMhqVHLMOqu?usp=sharing).


### **Screencast**

```{r, echo = FALSE}
library("htmltools")
library("vembedr")

embed_url("https://youtu.be/w4axZOt7x_E")
```


### **Analysis Summary**

#### *Project Scope*
The motivation of this project is answer the age-old question, "I don't know, what are you in the mood to eat tonight?".

#### *Data* 
The source of the data: [Yelp](https://www.yelp.com/) is a well known website that allows users to review and rate restaurants they've been to, so that this knowledge can be shared with others. Yelp users, or "Yelpers" have written over 163 million reviews since the website's inception in 2014, with 32 million unique users every month.

#### *Approaches*
We performed exploratory statistical analysis in order to look into this dataset. Originally the dataset contained information for all types of businesses, so we narrowed it to just restaurants in Las Vegas. We were able to look at restaurant information by neighborhood and category type too. 

#### *Visualizations*
We include 4 plots with our analysis. The first plot looks at whether people were more likely to review a restaurant if they had a more extreme opinion on their experience (like a 1 star or 5 star rating). Another graph displays if there were any geographic areas that had a high concentration of low rated or high rated restaurants. The last two graphs look at the breakdown of restaurant categories by neighborhood to see if certain neighborhood had concentrations of a specific type of restaurant. We looked at this two different ways, coloring by stars in one and coloring by category in the other. 

#### *Results*
There were 3476 restaurants included in our analysis. The Strip is the neighborhood with the most restaurants at 613, and Anthem has the least with only 10 restaurants. However, we noticed during our exploratory analysis that while The Strip had the highest number of restaurants, it received the 3rd worst restaurant ratings on average. It is important to note that variations in star ratings differed significantly by both neighborhood and by restaurant category were significant according to our analysis. 